# Generated by Django 3.2.9 on 2021-12-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone_name',
            new_name='phone_number',
        ),
    ]
