# Generated by Django 3.2.9 on 2021-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
