# Generated by Django 3.2.9 on 2021-12-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_apply_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_job', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
